config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [:index, :show, :new, :create] do
    resources :reviews, only: [ :new, :create,:show, :index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
 validates :name, :address, :category, :phone_number, presence: true
 CATEGORY = [ "chinese", "italian", "japanese", "french", "belgian"]
validates :category, inclusion: CATEGORY
has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, :rating, presence: true
  validates :rating, numericality: { only_integer: true }, inclusion: { in: 0..5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurants_path(@restaurant)
    else
      render "new"
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @reviews = Review.where(:restaurant_id => params[:restaurant_id])
  end
  def new
    # we need @restaurant in our `simple_form_for`
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end
  def create
    @review = Review.new(review_params)
    # we need `restaurant_id` to associate review with corresponding restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    @review.save
    redirect_to restaurant_reviews_path(@restaurant)
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-light bg-light">
  <div class="container-fluid">
    <span class="navbar-brand mb-0 h1">Our Restaurant</span>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <%= render "layouts/navbar" %>
   <div class="container mt-5 " >
    <%= yield %>
  </div>
  </body>
</html>

app/views/restaurants/index.html.erb
<ul class="list-group w-25 mx-auto">
  <% @restaurants.each do |restaurant|%>
  <li class="list-group-item"><%= link_to restaurant.name, restaurant_path(restaurant) %></li>
  <% end %>
</ul>

<%= link_to "+", new_restaurant_path, class:"btn btn-outline-success"%>

app/views/restaurants/new.html.erb
<div >
<%= simple_form_for [ @restaurant] do |f| %>
<%= f.input :name %>
<%= f.input :address%>
<%= f.input :phone_number %>
<%= f.input :category, collection: Restaurant::CATEGORY %>
<%= f.submit "Add new restaurant!", class: "btn btn-primary" %>
<% end %>
</div>

app/views/restaurants/show.html.erb
<div class="card mx-auto" style="width: 18rem;">
  <div class="card-body" >
    <h5 class="card-title"><%= @restaurant.name %></h5>
    <hr/>
    <h6 class="card-subtitle mb-2 text-muted"><%= @restaurant.category %></h6>
    <p class="card-text"><%= @restaurant.address %></p>
     <h6 class="card-subtitle mb-2 text-muted"><%= @restaurant.phone_number %></h6>
 <hr/>
 <%= link_to "review", restaurant_reviews_path(@restaurant), class: "card-link"%>
  </div>
</div>

app/views/reviews/create.html.erb
<h1>hi</h1>

app/views/reviews/index.html.erb
<ul class="list-group w-50 mx-auto">
  <% @reviews.each do |review|%>
  <li class="list-group-item d-flex justify-content-between"><%= review.content %>
    <span class="badge bg-warning text-white"><%= review.rating %></span>
  </li>
  <% end %>
</ul>
<%= link_to "+", new_restaurant_review_path, class:"btn btn-outline-success"%>

app/views/reviews/new.html.erb
<div >
<%= simple_form_for [ @restaurant, @review ] do |f| %>
<%= f.input :content %>
<%= f.input :rating %>
<%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>
</div>